<?php

namespace Oylex\SpamJudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextSampleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextSampleRepository extends EntityRepository
{
    public function getUnprocessedSamples()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.tokenProcessed = :tokenProcessed AND s.type != :type')
            ->setParameter('tokenProcessed', false)
            ->setParameter('type', 0);

        return $qb->getQuery()
            ->getResult();
    }
}
