<?php

namespace Oylex\SpamJudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TokenCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenCountRepository extends EntityRepository
{
}
